export const typesOfCars: string[] = [
    "Berline",
    "Break",
    "Cabriolet",
    "Citadine",
    "Coupé",
    "Monospace",
    "SUV",
    "Utilitaire",
    "Voiture de sport",
    "Voiture familiale",
    "Voiture électrique",
    "Voiture hybride",
    "Voiture compacte",
    "Voiture de luxe",
    "Voiture de collection",
    "Voiture économique",
    "Voiture polyvalente",
    "Voiture routière",
    "Voiture tout-terrain"
];

export const carMarques: string[] = [
    "Dacia",
    "Renault",
    "Peugeot",
    "Citroën",
    "Volkswagen",
    "Ford",
    "Fiat",
    "Hyundai",
    "Kia",
    "Toyota",
    "Nissan",
    "Mercedes-Benz",
    "BMW",
    "Audi",
    "Skoda",
    "Seat",
    "Mitsubishi",
    "Chevrolet",
    "Opel",
    "Suzuki",
    "Honda",
    "Mazda",
    "Jeep",
    "Volvo",
    "Land Rover",
    "Jaguar",
    "Mini",
    "Lexus",
    "Subaru",
    "Alfa Romeo",
    "Chery",
    "Geely",
    "Great Wall",
    "Isuzu",
    "Mahindra",
    "Porsche",
    "SsangYong",
    "Tata",
    "Tesla",
    "Infiniti",
    "Ferrari",
    "Lamborghini",
    "Maserati",
    "Bentley",
    "Rolls-Royce",
    "McLaren",
    "Aston Martin",
    "Bugatti",
    "Lotus",
    "Maybach",
    "Morgan",
    "Pagani",
    "Smart",
];